# -*- coding: utf-8 -*-
"""untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/sir20409/4f91ae05a4e908c7db183c52392de0f9/untitled8.ipynb
"""

import sklearn
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression

from google.colab import drive
drive.mount('/drive')

import glob

# 드라이브 전체에서 '동아리' 폴더 속 파일들을 찾습니다.
all_dongari_files = glob.glob('/drive/MyDrive/**/동아리리/*', recursive=True)

for file_path in all_dongari_files:
    print(file_path)

dong_data_2021 = pd.read_excel('/drive/MyDrive/동아리리/21년도 데이터.xlsx')
dong_data_2021

x = dong_data_2021.iloc[:,1:4].values
y1 = dong_data_2021.iloc[:,-2].values
y2 = dong_data_2021.iloc[:,-1].values

regy1 = LinearRegression()
regy1.fit(x,y1)

regy1.coef_

type(regy1.intercept_)

def y1_result(x1,x2,x3):
  X=[x1,x2,x3]
  yy11 = regy1.intercept_
  for i,j in zip(regy1.coef_,X):
     yy11 += j*i
  return yy11

y1_result(290120,3869,2313)

regy2 = LinearRegression()
regy2.fit(x,y2)

def y2_result(x1,x2,x3):
  X=[x1,x2,x3]
  yy22 = regy2.intercept_
  for i,j in zip(regy2.coef_,X):
    yy22 += j*i
  return yy22

y2_result(78500,3333,1287)

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

# 1. 가상 데이터 생성 (4개의 중심점을 가진 400개 데이터)
x,y = dong_data_2021.iloc[:,2].values ,dong_data_2021.iloc[:,-2].values

X=[]
for i in range(0,len(x)):
  X.append([x[i],y[i]])

X = np.array(X)

# 2. 엘보우 방법 (최적의 K 탐색을 위해 1부터 10까지 반복 학습)
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42, n_init='auto')
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)
k_range = range(1,11)
# 3. 최종 K-Means 모델 학습 (엘보우 결과인 K=4로 설정)
p1 = np.array([k_range[0], wcss[0]])
p2 = np.array([k_range[-1], wcss[-1]])

distances = []
for i in range(len(k_range)):
    p3 = np.array([k_range[i], wcss[i]])
    # 직선(p1-p2)과 점(p3) 사이의 거리 계산
    distance = np.abs(np.cross(p2 - p1, p1 - p3)) / np.linalg.norm(p2 - p1)
    distances.append(distance)

# 거리가 가장 먼 인덱스의 K 값을 자동으로 선택
optimal_k = k_range[np.argmax(distances)]

kmeans = KMeans(n_clusters=optimal_k, init='k-means++', random_state=42, n_init='auto')
y_kmeans = kmeans.fit_predict(X)
centroids = kmeans.cluster_centers_

# 4. 시각화 (두 개의 그래프를 좌우로 나란히 출력)
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# [왼쪽] 엘보우 그래프
axes[0].plot(range(1, 11), wcss, marker='o', linestyle='--')
axes[0].set_title("The Elbow Method")
axes[0].set_xlabel("Number of Clusters (K)")
axes[0].set_ylabel("WCSS (Inertia)")

# [오른쪽] K-Means 군집화 결과 (데이터 포인트 + 빨간색 X 중심점)
axes[1].scatter(X[:, 0], X[:, 1], c=y_kmeans, s=30, cmap='viridis', label='Data Points')
axes[1].scatter(centroids[:, 0], centroids[:, 1], c='red', s=200, alpha=0.9, marker='X', label='Centroids')
axes[1].set_title(f"K-Means Clustering (K={optimal_k})")
axes[1].legend()

plt.tight_layout()
plt.show()
